package:
  name: blaze
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: ../

requirements:
  run:
    - blaze-core
    - h5py
    - cytoolz
    - pytables
    - pymongo
    - numba
    - bcolz
    - unittest2 [py26]

test:
  requires:
    - pytest
    - coverage

  commands:
    - py.test -x --pyargs blaze

about:
  home: http://blaze.pydata.org
  license: BSD
