package: blaze
user: blaze

platform:
  - linux-64
  - linux-32
  - osx-64
  - win-64
engine:
  - python=2.6
  - python=2.7
  - python=3.3
  - python=3.4

install:
  - conda config --add channels blaze

before_script:
  - python -V

script:
  - conda build conda.recipe

build_targets: conda

notifications:
  email:
    recipients: ['ben.zaitlen@continuum.io', 'mrocklin@continuum.io']
