language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

branches:
  only:
    - master
    - devel
    - release
    - py3

# Note: conda is not available for anything but python 2.7. So below we try to install
# conda in 2.7 and use conda to install dependencies in the virtualenv for version x.y
install:
  # Install conda
  - sudo pip install conda
  # Install dependencies
  - sudo conda init
  - conda create -p $HOME/py -c https://conda.binstar.org/mwiebe --yes nose cython numpy dynd-python pycparser pyparsing pyyaml flask pytables cffi pip "python=$TRAVIS_PYTHON_VERSION"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then conda install -p $HOME/py --yes unittest2; fi
  - export PATH=$HOME/py/bin:$PATH
  - pip install git+http://github.com/ContinuumIO/datashape
  - pip install git+http://github.com/ContinuumIO/blz
  - pip install git+http://github.com/pykit/pykit
  # Install Blaze
  - python setup.py install

script: cd $HOME; $HOME/py/bin/python -c 'import blaze; blaze.test(exit=True)'

notifications:
  email: false
  flowdock: "b08b3ba4fb86fa48121e90b5f67ccb75"
  on_success: "change"
  on_failure: "always" # "change"
