{% set data = load_setuptools() %}

package:
  name: blaze
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  entry_points:
    - blaze-server = blaze.server.spider:_main

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    {% for req in data.get('setup_requires', []) -%}
    - {{req}}
    {% endfor %}
  run:
    - python
    {% for req in data.get('install_requires', []) -%}
    - {{req}}
    {% endfor %}

test:
  imports:
    - blaze
  requires:
    {% for req in data.get('tests_require', []) -%}
    - {{req}}
    {% endfor %}
  commands:
    - py.test -vx --doctest-modules --doctest-ignore-import-errors --pyargs blaze -rsxX

about:
  home: http://blaze.pydata.org
  license: BSD
